M48
; DRILL file {KiCad 7.0.7} date Sat Nov 25 21:21:36 2023
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-11-25T21:21:36+09:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.7
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
%
G90
G05
T1
X60.96Y-68.58
X60.96Y-128.27
X236.22Y-68.58
X236.22Y-128.27
T0
M30
